// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOeYJntBRKJlkZhq_EE1tYQLysIcbu5bw',
    appId: '1:920531833273:web:63f89944e4436d2673e668',
    messagingSenderId: '920531833273',
    projectId: 'possible-ace-410212',
    authDomain: 'possible-ace-410212.firebaseapp.com',
    storageBucket: 'possible-ace-410212.appspot.com',
    measurementId: 'G-4CMJ8YV1J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwq5IoMaNYwxGyQTjMUyVuVw-uouRtyic',
    appId: '1:920531833273:android:ff2b6d53819983ad73e668',
    messagingSenderId: '920531833273',
    projectId: 'possible-ace-410212',
    storageBucket: 'possible-ace-410212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQM7lkQ2BAFmI8e1NKXNtk0OxS5cCqdMk',
    appId: '1:920531833273:ios:752dc3197c9eb82e73e668',
    messagingSenderId: '920531833273',
    projectId: 'possible-ace-410212',
    storageBucket: 'possible-ace-410212.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQM7lkQ2BAFmI8e1NKXNtk0OxS5cCqdMk',
    appId: '1:920531833273:ios:1ec72e18edd76cd673e668',
    messagingSenderId: '920531833273',
    projectId: 'possible-ace-410212',
    storageBucket: 'possible-ace-410212.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
